export type Difficulty = "Easy" | "Medium" | "Hard"

export type PracticeTopic = {
  id: string
  title: string
  description: string
}

export type PracticeList = {
  id: string
  title: string
  description: string
  accent: "primary" | "emerald" | "amber" | "rose" | "cyan"
}

export type PracticeProblem = {
  id: string
  number: number
  title: string
  difficulty: Difficulty
  topicId: string
  pattern: string
  tags: string[]
  companies: string[]
  listIds: string[]
  locked?: boolean
}

export const practiceLists: PracticeList[] = [
  {
    id: "core-skills",
    title: "Core Skills",
    description: "Implementation drills for data structures and algorithms.",
    accent: "primary",
  },
  {
    id: "blind-75",
    title: "Blind 75",
    description: "A focused set for high-signal review.",
    accent: "emerald",
  },
  {
    id: "neetcode-150",
    title: "NeetCode 150",
    description: "The primary interview prep track.",
    accent: "amber",
  },
  {
    id: "neetcode-200",
    title: "NeetCode 200",
    description: "An extended track with 50 additional problems.",
    accent: "rose",
  },
  {
    id: "neetcode-all",
    title: "NeetCode All",
    description: "Everything on the practice hub in one place.",
    accent: "cyan",
  },
]

export const practiceTopics: PracticeTopic[] = [
  {
    id: "arrays",
    title: "Arrays & Hashing",
    description: "Frequency maps, sets, and indexed scans",
  },
  {
    id: "two-pointers",
    title: "Two Pointers",
    description: "Opposing pointers and slow/fast scans",
  },
  {
    id: "stack",
    title: "Stack",
    description: "Monotonic stacks, parsing, and nesting",
  },
  {
    id: "binary-search",
    title: "Binary Search",
    description: "Boundary search and answer-space reduction",
  },
  {
    id: "linked-list",
    title: "Linked List",
    description: "Pointer rewiring and cycle patterns",
  },
  {
    id: "trees",
    title: "Trees",
    description: "Traversal, recursion, and BST properties",
  },
  {
    id: "heap",
    title: "Heap / Priority Queue",
    description: "Top-K and priority-driven selection",
  },
  {
    id: "graphs",
    title: "Graphs",
    description: "BFS, DFS, shortest paths, and ordering",
  },
  {
    id: "dynamic-programming",
    title: "Dynamic Programming",
    description: "State transitions and recurrence design",
  },
  {
    id: "intervals",
    title: "Intervals",
    description: "Merging, scheduling, and overlap checks",
  },
]

export const practiceProblems: PracticeProblem[] = [
  {
    id: "design-dynamic-array",
    number: 101,
    title: "Design Dynamic Array (Resizable Array)",
    difficulty: "Easy",
    topicId: "arrays",
    pattern: "Resizable storage",
    tags: ["Array", "Design"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
  },
  {
    id: "design-singly-linked-list",
    number: 102,
    title: "Design Singly Linked List",
    difficulty: "Easy",
    topicId: "linked-list",
    pattern: "Pointer wiring",
    tags: ["Linked List", "Design"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
  },
  {
    id: "design-double-ended-queue",
    number: 103,
    title: "Design Double-ended Queue",
    difficulty: "Easy",
    topicId: "linked-list",
    pattern: "Head/tail pointers",
    tags: ["Queue", "Design"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "design-binary-search-tree",
    number: 104,
    title: "Design Binary Search Tree",
    difficulty: "Medium",
    topicId: "trees",
    pattern: "Ordered tree operations",
    tags: ["Tree", "Design"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "design-hash-table",
    number: 105,
    title: "Design Hash Table",
    difficulty: "Medium",
    topicId: "arrays",
    pattern: "Hash buckets",
    tags: ["Hash Table", "Design"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "design-heap",
    number: 106,
    title: "Design Heap",
    difficulty: "Medium",
    topicId: "heap",
    pattern: "Heap invariant",
    tags: ["Heap", "Design"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "design-graph",
    number: 107,
    title: "Design Graph",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "Adjacency storage",
    tags: ["Graph", "Design"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "design-disjoint-set",
    number: 108,
    title: "Design Disjoint Set (Union-Find)",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "Union by rank",
    tags: ["Graph", "Union Find"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "design-segment-tree",
    number: 109,
    title: "Design Segment Tree",
    difficulty: "Hard",
    topicId: "trees",
    pattern: "Range query tree",
    tags: ["Tree", "Design"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "insertion-sort",
    number: 110,
    title: "Insertion Sort",
    difficulty: "Easy",
    topicId: "arrays",
    pattern: "Incremental ordering",
    tags: ["Array", "Sorting"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
  },
  {
    id: "merge-sort",
    number: 111,
    title: "Merge Sort",
    difficulty: "Medium",
    topicId: "arrays",
    pattern: "Divide and conquer",
    tags: ["Array", "Sorting"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "quick-sort",
    number: 112,
    title: "Quick Sort",
    difficulty: "Medium",
    topicId: "arrays",
    pattern: "Partitioning",
    tags: ["Array", "Sorting"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "matrix-depth-first-search",
    number: 113,
    title: "Matrix Depth-First Search",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "Grid DFS",
    tags: ["DFS", "Matrix"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "matrix-breadth-first-search",
    number: 114,
    title: "Matrix Breadth-First Search",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "Grid BFS",
    tags: ["BFS", "Matrix"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "prims-algorithm",
    number: 115,
    title: "Prim's Algorithm",
    difficulty: "Hard",
    topicId: "graphs",
    pattern: "Minimum spanning tree",
    tags: ["Graph", "Heap"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "kruskals-algorithm",
    number: 116,
    title: "Kruskal's Algorithm",
    difficulty: "Hard",
    topicId: "graphs",
    pattern: "Union-find MST",
    tags: ["Graph", "Union Find"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "topological-sort",
    number: 117,
    title: "Topological Sort",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "DAG ordering",
    tags: ["Graph", "DFS", "BFS"],
    companies: ["Core Skills"],
    listIds: ["core-skills", "neetcode-all"],
    locked: true,
  },
  {
    id: "contains-duplicate",
    number: 1,
    title: "Contains Duplicate",
    difficulty: "Easy",
    topicId: "arrays",
    pattern: "Hash set",
    tags: ["Array", "Hash Table"],
    companies: ["Amazon", "Apple", "Google"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "valid-anagram",
    number: 2,
    title: "Valid Anagram",
    difficulty: "Easy",
    topicId: "arrays",
    pattern: "Frequency map",
    tags: ["String", "Hash Table"],
    companies: ["Microsoft", "Uber", "Bloomberg"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "two-sum",
    number: 3,
    title: "Two Sum",
    difficulty: "Easy",
    topicId: "arrays",
    pattern: "One-pass map",
    tags: ["Array", "Hash Table"],
    companies: ["Amazon", "Google", "Meta"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "group-anagrams",
    number: 4,
    title: "Group Anagrams",
    difficulty: "Medium",
    topicId: "arrays",
    pattern: "Canonical key",
    tags: ["String", "Hash Table", "Sorting"],
    companies: ["Amazon", "Meta", "Uber"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "top-k-frequent-elements",
    number: 5,
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    topicId: "arrays",
    pattern: "Bucket count",
    tags: ["Array", "Hash Table", "Heap"],
    companies: ["Amazon", "Meta", "Yelp"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "product-of-array-except-self",
    number: 6,
    title: "Product of Array Except Self",
    difficulty: "Medium",
    topicId: "arrays",
    pattern: "Prefix/suffix",
    tags: ["Array", "Prefix Sum"],
    companies: ["Meta", "Amazon", "Microsoft"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "valid-sudoku",
    number: 7,
    title: "Valid Sudoku",
    difficulty: "Medium",
    topicId: "arrays",
    pattern: "Constraint sets",
    tags: ["Array", "Hash Table", "Matrix"],
    companies: ["Apple", "Amazon", "Snap"],
    listIds: ["neetcode-150", "neetcode-200", "neetcode-all"],
    locked: true,
  },
  {
    id: "valid-palindrome",
    number: 8,
    title: "Valid Palindrome",
    difficulty: "Easy",
    topicId: "two-pointers",
    pattern: "Opposing scan",
    tags: ["String", "Two Pointers"],
    companies: ["Meta", "Microsoft", "Apple"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "two-sum-ii",
    number: 9,
    title: "Two Sum II - Input Array Is Sorted",
    difficulty: "Medium",
    topicId: "two-pointers",
    pattern: "Sorted bounds",
    tags: ["Array", "Two Pointers", "Binary Search"],
    companies: ["Amazon", "Adobe", "Bloomberg"],
    listIds: ["neetcode-150", "neetcode-200", "neetcode-all"],
  },
  {
    id: "container-with-most-water",
    number: 10,
    title: "Container With Most Water",
    difficulty: "Medium",
    topicId: "two-pointers",
    pattern: "Greedy bounds",
    tags: ["Array", "Two Pointers", "Greedy"],
    companies: ["Amazon", "Google", "Meta"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "trapping-rain-water",
    number: 11,
    title: "Trapping Rain Water",
    difficulty: "Hard",
    topicId: "two-pointers",
    pattern: "Max boundaries",
    tags: ["Array", "Two Pointers", "Dynamic Programming"],
    companies: ["Amazon", "Apple", "Goldman Sachs"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
    locked: true,
  },
  {
    id: "valid-parentheses",
    number: 12,
    title: "Valid Parentheses",
    difficulty: "Easy",
    topicId: "stack",
    pattern: "Matching stack",
    tags: ["String", "Stack"],
    companies: ["Amazon", "Meta", "Microsoft"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "min-stack",
    number: 13,
    title: "Min Stack",
    difficulty: "Medium",
    topicId: "stack",
    pattern: "Auxiliary state",
    tags: ["Stack", "Design"],
    companies: ["Amazon", "Bloomberg", "Uber"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "evaluate-reverse-polish-notation",
    number: 14,
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    topicId: "stack",
    pattern: "Expression stack",
    tags: ["Array", "Math", "Stack"],
    companies: ["LinkedIn", "Amazon", "Google"],
    listIds: ["neetcode-150", "neetcode-200", "neetcode-all"],
  },
  {
    id: "daily-temperatures",
    number: 15,
    title: "Daily Temperatures",
    difficulty: "Medium",
    topicId: "stack",
    pattern: "Monotonic stack",
    tags: ["Array", "Stack"],
    companies: ["Amazon", "Google", "Meta"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "binary-search",
    number: 16,
    title: "Binary Search",
    difficulty: "Easy",
    topicId: "binary-search",
    pattern: "Closed interval",
    tags: ["Array", "Binary Search"],
    companies: ["Microsoft", "Amazon", "Apple"],
    listIds: ["neetcode-150", "neetcode-200", "neetcode-all"],
  },
  {
    id: "search-a-2d-matrix",
    number: 17,
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    topicId: "binary-search",
    pattern: "Flattened index",
    tags: ["Array", "Binary Search", "Matrix"],
    companies: ["Amazon", "Meta", "Google"],
    listIds: ["neetcode-150", "neetcode-200", "neetcode-all"],
  },
  {
    id: "find-minimum-in-rotated-sorted-array",
    number: 18,
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    topicId: "binary-search",
    pattern: "Pivot detection",
    tags: ["Array", "Binary Search"],
    companies: ["Amazon", "Microsoft", "Bloomberg"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "reverse-linked-list",
    number: 19,
    title: "Reverse Linked List",
    difficulty: "Easy",
    topicId: "linked-list",
    pattern: "Pointer reversal",
    tags: ["Linked List", "Recursion"],
    companies: ["Amazon", "Apple", "Meta"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "merge-two-sorted-lists",
    number: 20,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    topicId: "linked-list",
    pattern: "Dummy head",
    tags: ["Linked List", "Recursion"],
    companies: ["Amazon", "Microsoft", "Apple"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "linked-list-cycle",
    number: 21,
    title: "Linked List Cycle",
    difficulty: "Easy",
    topicId: "linked-list",
    pattern: "Fast/slow pointers",
    tags: ["Linked List", "Two Pointers"],
    companies: ["Amazon", "Bloomberg", "Microsoft"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "invert-binary-tree",
    number: 22,
    title: "Invert Binary Tree",
    difficulty: "Easy",
    topicId: "trees",
    pattern: "Recursive swap",
    tags: ["Tree", "DFS", "BFS"],
    companies: ["Google", "Amazon", "Microsoft"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "maximum-depth-of-binary-tree",
    number: 23,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    topicId: "trees",
    pattern: "Recursive depth",
    tags: ["Tree", "DFS", "BFS"],
    companies: ["Amazon", "LinkedIn", "Meta"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "same-tree",
    number: 24,
    title: "Same Tree",
    difficulty: "Easy",
    topicId: "trees",
    pattern: "Paired traversal",
    tags: ["Tree", "DFS"],
    companies: ["Amazon", "Bloomberg", "LinkedIn"],
    listIds: ["neetcode-150", "neetcode-200", "neetcode-all"],
  },
  {
    id: "kth-largest-element-in-a-stream",
    number: 25,
    title: "Kth Largest Element in a Stream",
    difficulty: "Easy",
    topicId: "heap",
    pattern: "Bounded min-heap",
    tags: ["Tree", "Design", "Heap"],
    companies: ["Amazon", "Google", "Meta"],
    listIds: ["neetcode-150", "neetcode-200", "neetcode-all"],
  },
  {
    id: "last-stone-weight",
    number: 26,
    title: "Last Stone Weight",
    difficulty: "Easy",
    topicId: "heap",
    pattern: "Max heap simulation",
    tags: ["Array", "Heap", "Simulation"],
    companies: ["Google", "Amazon", "Bloomberg"],
    listIds: ["neetcode-150", "neetcode-200", "neetcode-all"],
  },
  {
    id: "k-closest-points-to-origin",
    number: 27,
    title: "K Closest Points to Origin",
    difficulty: "Medium",
    topicId: "heap",
    pattern: "Top-K heap",
    tags: ["Array", "Math", "Heap"],
    companies: ["Amazon", "Meta", "Apple"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "number-of-islands",
    number: 28,
    title: "Number of Islands",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "Grid DFS",
    tags: ["Array", "DFS", "BFS", "Matrix"],
    companies: ["Amazon", "Meta", "Microsoft"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "clone-graph",
    number: 29,
    title: "Clone Graph",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "Graph traversal map",
    tags: ["Hash Table", "DFS", "BFS", "Graph"],
    companies: ["Amazon", "Meta", "Google"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "course-schedule",
    number: 30,
    title: "Course Schedule",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "Topological sort",
    tags: ["DFS", "BFS", "Graph"],
    companies: ["Amazon", "Google", "Meta"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "dijkstras-algorithm",
    number: 31,
    title: "Dijkstra's Algorithm",
    difficulty: "Medium",
    topicId: "graphs",
    pattern: "Priority queue shortest path",
    tags: ["Graph", "Heap", "Shortest Path"],
    companies: ["Google", "Amazon", "Uber"],
    listIds: ["core-skills", "neetcode-all"],
  },
  {
    id: "climbing-stairs",
    number: 32,
    title: "Climbing Stairs",
    difficulty: "Easy",
    topicId: "dynamic-programming",
    pattern: "Fibonacci state",
    tags: ["Math", "Dynamic Programming"],
    companies: ["Amazon", "Adobe", "Apple"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "house-robber",
    number: 33,
    title: "House Robber",
    difficulty: "Medium",
    topicId: "dynamic-programming",
    pattern: "Take/skip state",
    tags: ["Array", "Dynamic Programming"],
    companies: ["Amazon", "LinkedIn", "Google"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "coin-change",
    number: 34,
    title: "Coin Change",
    difficulty: "Medium",
    topicId: "dynamic-programming",
    pattern: "Unbounded knapsack",
    tags: ["Array", "BFS", "Dynamic Programming"],
    companies: ["Amazon", "Bloomberg", "Meta"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "longest-increasing-subsequence",
    number: 35,
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    topicId: "dynamic-programming",
    pattern: "Patience sorting",
    tags: ["Array", "Binary Search", "Dynamic Programming"],
    companies: ["Amazon", "Google", "Microsoft"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
    locked: true,
  },
  {
    id: "merge-intervals",
    number: 36,
    title: "Merge Intervals",
    difficulty: "Medium",
    topicId: "intervals",
    pattern: "Sort and merge",
    tags: ["Array", "Sorting"],
    companies: ["Amazon", "Google", "Meta"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
  {
    id: "insert-interval",
    number: 37,
    title: "Insert Interval",
    difficulty: "Medium",
    topicId: "intervals",
    pattern: "Three-phase merge",
    tags: ["Array"],
    companies: ["Meta", "Google", "Amazon"],
    listIds: ["neetcode-150", "blind-75", "neetcode-200", "neetcode-all"],
  },
]

export const practiceTopicById = Object.fromEntries(
  practiceTopics.map((topic) => [topic.id, topic])
) as Record<string, PracticeTopic>

export const practiceListById = Object.fromEntries(
  practiceLists.map((list) => [list.id, list])
) as Record<string, PracticeList>

export const practiceProblemById = Object.fromEntries(
  practiceProblems.map((problem) => [problem.id, problem])
) as Record<string, PracticeProblem>
